services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: vite_gourmand
      DB_USER: vg
      DB_PASS: vgpass
      DB_CHARSET: utf8mb4
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: vite_gourmand
      MYSQL_USER: vg
      MYSQL_PASSWORD: vgpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  db_data:
